language: objective-c
podfile: Demo/Podfile
cache:
- bundler
- cocoapods
before_install:
- gem install cocoapods
- pod install
script: xctool -workspace Demo/Demo.xcworkspace -scheme Demo -sdk iphonesimulator build test
